"""
自动生成的静态 import 列表
用于 Nuitka --module 编译时能看到所有子模块
由 scripts/generate_static_imports.py 自动生成，请勿手动编辑
"""

# ruff: noqa: F401

from app.models import agenda
from app.models import agent_message
from app.models import agent_session
from app.models import base_model
from app.models import checkpoint
from app.models import conversation_message
from app.models import example
from app.models import file
from app.models import flow
from app.models import flow_edge
from app.models import flow_execution
from app.models import flow_node
from app.models import flow_snapshot
from app.models import global_config
from app.models import knowledge_base
from app.models import knowledge_document
from app.models import knowledge_document_segment
from app.models import knowledge_document_title
from app.models import knowledge_insight
from app.models import mcp_server
from app.models import memory
from app.models import node_execution
from app.models import scheduled_task
from app.models import skill
from app.models import todo_item
from app.models import token_usage
from app.models import ws_gateway
from app.models import ws_gateway_call_record
from app.schemas import agenda_schema
from app.schemas import agent_schema
from app.schemas import ai_flow_schema
from app.schemas import base_schema
from app.schemas import conversation_schema
from app.schemas import example_schema
from app.schemas import execution_schema
from app.schemas import file_schema
from app.schemas import flow_edge_schema
from app.schemas import flow_node_schema
from app.schemas import flow_schema
from app.schemas import flow_snapshot_schema
from app.schemas import global_config_schema
from app.schemas import knowledge_insight_schema
from app.schemas import knowledge_schema
from app.schemas import marketplace_schema
from app.schemas import mcp_server_schema
from app.schemas import memory_schema
from app.schemas import scheduled_task_schema
from app.schemas import skill_schema
from app.schemas import statistics_schema
from app.schemas import todo_schema
from app.schemas import ws_gateway_schema
from app.services import agenda_service
from app.services import agent_conversation_service
from app.services import agent_executor_service
from app.services import base_executor_service
from app.services import base_service
from app.services import builtin_agent_service
from app.services import conversation_service
from app.services import embedding_service
from app.services import example_serveice
from app.services import file_service
from app.services import flow_execution_service
from app.services import flow_executor_service
from app.services import flow_service
from app.services import flow_snapshot_service
from app.services import flow_template_service
from app.services import flow_transfer_service
from app.services import global_config_service
from app.services import interrupt_service
from app.services import knowledge_base_service
from app.services import knowledge_document_service
from app.services import knowledge_insight_service
from app.services import knowledge_title_service
from app.services import marketplace_import_service
from app.services import marketplace_service
from app.services import mcp_server_service
from app.services import memory_service
from app.services import node_config_helper
from app.services import scheduled_task_service
from app.services import scheduler_service
from app.services import skill_service
from app.services import todo_service
from app.services import token_usage_service
from app.services import tool_approval_service
from app.services import vector_store_service
from app.services import ws_gateway_service
from app.services import ws_manager
from app.middleware import auth_middleware
from app.middleware import exception_middleware
from app.middleware import security_middleware
from app.config import app_setup
from app.config import build_utils
from app.config import database
from app.config import lifespan
from app.config import logging_config
from app.config import settings
from app.config import tray
from app.config import version
from app.constants import node_types
from app.utils import database_util
from app.utils import db_schema_validator
from app.utils import document_processor
from app.utils import flow_utils
from app.utils import loader
from app.utils import media_file
from app.utils import media_resolver
from app.utils import message_utils
from app.utils import pdf_parser
from app.utils import reasoning_llm
from app.utils import skill_uploader
from app.utils import sse
from app.utils import user_util
from app.agent_flow.node_handlers import agenda_handler
from app.agent_flow.node_handlers import api_handler
from app.agent_flow.node_handlers import base_handler
from app.agent_flow.node_handlers import card_handlers
from app.agent_flow.node_handlers import control_handlers
from app.agent_flow.node_handlers import human_handler
from app.agent_flow.node_handlers import intent_router_handler
from app.agent_flow.node_handlers import knowledge_handler
from app.agent_flow.node_handlers import llm_factory
from app.agent_flow.node_handlers import llm_message_builder
from app.agent_flow.node_handlers import llm_stream
from app.agent_flow.node_handlers import llm_tool_executor
from app.agent_flow.node_handlers import llm_tool_handler
from app.agent_flow.node_handlers import loop_handler
from app.agent_flow.node_handlers import mcp_handler
from app.agent_flow.node_handlers import memory_handler
from app.agent_flow.node_handlers import python_handler
from app.agent_flow.node_handlers import shell_handler
from app.agent_flow.node_handlers import skill_handler
from app.agent_flow.node_handlers import sub_agent_handler
from app.agent_flow.node_handlers import todo_handler
from app.agent_flow.ai_provider import anthropic
from app.agent_flow.ai_provider import base
from app.agent_flow.ai_provider import deepseek
from app.agent_flow.ai_provider import minimax
from app.agent_flow.ai_provider import openai_compatible
from app.agent_flow.ai_provider import qwen
from app.agent_flow.ai_provider import zhipu
from app.api import agenda_api
from app.api import agent_api
from app.api import ai_flow_api
from app.api import ai_provider_api
from app.api import auth_api
from app.api import base_api
from app.api import example_api
from app.api import execution_api
from app.api import file_api
from app.api import flow_api
from app.api import flow_edge_api
from app.api import flow_node_api
from app.api import flow_snapshot_api
from app.api import flow_template_api
from app.api import global_config_api
from app.api import knowledge_api
from app.api import knowledge_document_api
from app.api import knowledge_insight_api
from app.api import marketplace_api
from app.api import mcp_server_api
from app.api import memory_api
from app.api import scheduled_task_api
from app.api import skill_api
from app.api import statistics_api
from app.api import ws_gateway_api
from app.api import ws_api
from app.api import ws_trigger_api
